### ISSUE TITLE
code links failed

### ISSUE THREAD

**Issue by saber5433** [crowdAI/crowdai-musical-genre-recognition-starter-kit#2]
Some code links failed

**Comment by mdeff** [comment]
Indeed. Thanks for reporting.

* <https://gitlab.crowdai.org/viper/WWWMusicalGenreRecognitionChallenge> moved to <https://gitlab.crowdai.org/viper/crowdai-viper>. Fixed in a1c8692.
* <https://gitlab.crowdai.org/hglim/WWWMusicalGenreRecognitionChallenge> is not available anymore. Maybe the author removed it.
